### ISSUE TITLE
About macOS install script

### ISSUE THREAD

**Issue by CorellianAle** [loentar/ngrest#26] opened 2017-03-12 19:01 UTC
When you run the installation script on macOS, you get the message "Running Homebrew as root is extremely dangerous and no longer supported. As Homebrew does not drop privileges on installation you would be giving all build scripts full access to your system." and the installation ends.
It happened when your script tried to install CMAKE via homebrew when your script asked for password.

The second thing is usage of "bit.ly" url and "bash" command and -q0- flag. It looks really suspicious. It is a bad practice.

**Comment by loentar** [comment] 2017-03-14 12:01
Which is your brew and OSX version? I cannot reproduce this with 0.9.5 under OSX 10.11.6.

That line is just downloads an installation bash script using wget from url shortener (bit.ly) pointing github and pipe it to bash.
The `-qO-` flag may look suspicious only if you don't know what does it mean.  Actually it disables any output to error stream and tells wget to print downloaded file to stdout. Read `man wget` for details.

What is the good practice in your opinion?

**Comment by loentar** [comment] 2017-03-14 12:35
Please try this, I've added workaround to do not start brew under sudo.

**Comment by CorellianAle** [comment] 2017-03-14 13:52
I am using macOS 10.12.3 and homebrew 1.1.11.
I've run the script from scratch (I've remove all dependencies) and it worked fine now.

As for the short URL, bit.ly obscures the real URL, which makes it impossible to determine if the resource is to be trusted. It's basically the same as when Safari started to hide URL on mouseover.
I may be a bit paranoid, but I just decided to share my opinion.
It is true that I've never used `-q0-` flag before (never needed it) and overreacted a little. But usually, as a developer, I try to get as much info as possible and all `--quite` like flags scare a little)
Again, it is totally my opinion and I may be wrong.

**Comment by loentar** [comment] 2017-03-14 17:58
Well, if you prefer to control the whole process, this installation manual for you: https://github.com/loentar/ngrest/wiki/Build-ngrest-from-source-code

Closing the issue, as it works.

**Closed by loentar** 2017-03-14 17:58 UTC
